### ISSUE TITLE
FileNotFoundError: No such file or directory (os error 2): data/sa_crop/s2_split_iou.parquet

### ISSUE THREAD

**Issue by wuwuzhijing** [DarthReca/crop-field-segmentation-ukan#1]
I run 
`python main.py`
but an error occurs.

**Comment by DarthReca** [comment]
Added the file with f4e03ec

**Comment by wuwuzhijing** [comment]
> Added the file with [f4e03ec](https://github.com/DarthReca/crop-field-segmentation-ukan/commit/f4e03ec89801507d5dad38f1f3a239e56770b35c)

OK. Thanks!
